version: '2'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    depends_on:
      - app
  app:
    build:
      context: app
  service:
    build:
      context: service
    ports:
      - "8088:80"
    volumes:
      - ./tmp:/tmp
